/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.silver.happines

import io.ktor.server.engine.*
import io.ktor.server.netty.*
import com.example.plugins.*

fun main(args: Array<String>) {
    embeddedServer(Netty, commandLineEnvironment(args))
        .start(wait = true)
}